name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and generate lockfile
        run: |
          pnpm install --no-frozen-lockfile
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add pnpm-lock.yaml
          git commit -m "chore: update pnpm-lock.yaml [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Build
        run: |
          pnpm build
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4